blank_issues_enabled: true
contact_links:
  - name: Questions
    url: https://github.com/DCAN-Labs/nda-abcd-s3-downloader
    about: Please ask and answer questions related to the NDA downloader usage here.